#!/bin/dash

dir=".script"
statusDir="$dir/status"

if [ -d "$dir" ]; then
    echo "script-init: error: $dir already exists"
else
    mkdir "$dir"
    mkdir "$statusDir"

    for file in *; do
        if [ -f "$file" ]; then
            echo "$file - untracked" > "$statusDir/$file"
        fi
    done
    echo "Initialized empty script repository in $dir"
fi